#!/usr/bin/env node

/**
 * Auto-generate INDEX.md from issue files.
 * Run: node {{dirName}}/update-index.js
 *
 * Reads ./config.json (next to this script) for project name, statuses,
 * and categories. Filename grammar:
 *   YYYY-MM-DD_STATUS_category_short-slug.md
 */

const fs = require('fs');
const path = require('path');

const ISSUES_DIR = __dirname;
const INDEX_FILE = path.join(ISSUES_DIR, 'INDEX.md');
const ARCHIVE_DIR = path.join(ISSUES_DIR, 'archive');
const CONFIG_FILE = path.join(ISSUES_DIR, 'config.json');

const RESERVED = new Set(['INDEX.md', 'README.md', 'ISSUE_TEMPLATE.md', 'config.json']);

function loadConfig() {
  try {
    const raw = fs.readFileSync(CONFIG_FILE, 'utf-8');
    return JSON.parse(raw);
  } catch (err) {
    console.error(`Error: could not read ${CONFIG_FILE}`);
    console.error(`  ${err.message}`);
    process.exit(1);
  }
}

function escapeRegex(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function buildStatusRegex(statuses) {
  const alternatives = statuses.map(s => escapeRegex(s).replace(/-/g, '[-_]'));
  return new RegExp(`^(\\d{4}-\\d{2}-\\d{2})_(${alternatives.join('|')})_([^_]+)_(.+)\\.md$`);
}

function parseFilename(filename, regex) {
  const match = filename.match(regex);
  if (!match) return null;
  return {
    date: match[1],
    status: match[2].replace(/_/g, '-'),
    category: match[3],
    slug: match[4].replace(/-/g, ' '),
    filename
  };
}

function extractTitle(filepath) {
  try {
    const firstLine = fs.readFileSync(filepath, 'utf-8').split('\n')[0];
    return firstLine?.replace(/^#+\s*/, '').trim() || 'Untitled';
  } catch {
    return 'Untitled';
  }
}

function countArchived() {
  if (!fs.existsSync(ARCHIVE_DIR)) return 0;
  return fs.readdirSync(ARCHIVE_DIR).filter(f => f.endsWith('.md')).length;
}

function main() {
  const config = loadConfig();
  const statuses = Array.isArray(config.statuses) && config.statuses.length > 0
    ? config.statuses
    : null;
  if (!statuses || !statuses.every(s => typeof s === 'string' && s.length > 0)) {
    console.error('Error: config.statuses must be a non-empty array of strings.');
    console.error(`  Edit ${CONFIG_FILE} and re-run.`);
    process.exit(1);
  }
  const categories = config.categories || [];
  const projectName = config.projectName || 'Project';
  const resolvedLimit = config.indexResolvedLimit ?? 0;
  const lastStatus = statuses[statuses.length - 1];

  const regex = buildStatusRegex(statuses);

  const files = fs.readdirSync(ISSUES_DIR)
    .filter(f => f.endsWith('.md') && !RESERVED.has(f));

  const issues = [];
  for (const f of files) {
    const parsed = parseFilename(f, regex);
    if (!parsed) {
      console.warn(`  skipping unparseable filename: ${f}`);
      continue;
    }
    parsed.title = extractTitle(path.join(ISSUES_DIR, f));
    issues.push(parsed);
  }

  const grouped = Object.fromEntries(statuses.map(s => [s, []]));
  for (const issue of issues) {
    if (grouped[issue.status]) grouped[issue.status].push(issue);
  }

  for (const arr of Object.values(grouped)) {
    arr.sort((a, b) => a.date.localeCompare(b.date));
  }

  const archived = countArchived();
  const titleCase = (s) => s.split('-')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(' ');

  const renderList = (arr, limit, label) => {
    if (arr.length === 0) return '*None*\n';
    const slice = (limit && limit > 0) ? arr.slice(-limit).reverse() : arr;
    const body = slice.map(i => `- [\`${i.filename}\`](./${i.filename}) — ${i.title}`).join('\n');
    const truncated = (limit && limit > 0 && arr.length > limit)
      ? `\n\n*${arr.length - limit} earlier ${label} entries omitted*`
      : '';
    return body + truncated + '\n';
  };

  const sections = statuses
    .map(s => {
      const limit = (s === lastStatus) ? resolvedLimit : 0;
      if (grouped[s].length === 0) return '';
      const label = titleCase(s).toLowerCase();
      return `## ${titleCase(s)} (${grouped[s].length})\n${renderList(grouped[s], limit, label)}\n`;
    })
    .join('');

  const counts = statuses.map(s => `| ${titleCase(s)} | ${grouped[s].length} |`).join('\n');
  const categoriesLine = categories.length > 0
    ? `**Categories:** ${categories.map(c => `\`${c}\``).join(', ')}\n`
    : '';

  const content = `# ${projectName} — Issue Index

| Status | Count |
|--------|-------|
${counts}
| Archived | ${archived} |

**Naming:** \`[YYYY-MM-DD]_[STATUS]_[category]_[brief-description].md\`
${categoriesLine}
---

${sections}---
*Last Updated: ${new Date().toISOString().split('T')[0]}*
*Generated by: \`node {{dirName}}/update-index.js\`*
`;

  fs.writeFileSync(INDEX_FILE, content);

  const summary = statuses
    .map(s => `${grouped[s].length} ${s.toLowerCase()}`)
    .join(', ');
  console.log(`INDEX.md updated: ${issues.length} issues (${summary})`);
  if (archived > 0) console.log(`  ${archived} archived`);
}

main();
